#!/bin/sh

case $BUTTON in
  1) playerctl previous ;;
  2) playerctl play-pause ;;
  3) playerctl next ;;
  4) playerctl position 10+ ;;
  5) playerctl position 10- ;;
esac

case "$(playerctl status 2> /dev/null)" in
  # Media players generally show the pause icon while playing and the play icon
  # while paused.
  "Paused") STATUS="▶️" ;;
  "Playing") STATUS="⏸️" ;;
esac

[ -z "$STATUS" ] && exit 1

ARTIST="$(playerctl metadata artist)"
TITLE="$(playerctl metadata title)"
[ -n "$ARTIST" ] && [ -n "$TITLE" ] && SEPARATOR=" - "

printf "%s%s%s%s" "$STATUS" "$TITLE" "$SEPARATOR" "$ARTIST"

